baseurl= "https://blog.mletter.cn"
defaultContentLanguage = 'en'
[build]
  writeStats = true
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    lineNos = true
    lineNumbersInTable = false
    noClasses = false
[module]
[[module.imports]]
    path = 'github.com/hbstack/meta/recommended'
[[module.imports]]
    path = 'github.com/hugomods/icons/vendors/bootstrap'
[[module.imports]]
    path = 'github.com/hbstack/blog/modules/sidebar/profile'
[[module.imports]]
    path = 'github.com/hbstack/blog/modules/sidebar/taxonomies'
[[module.imports]]
    path = 'github.com/hbstack/google-fonts'
[[module.imports]]
    path = 'github.com/hbstack/code-block-panel'
[[module.imports]]
    path = 'github.com/hbstack/scrollbar'
[[module.imports]]
    path = 'github.com/hbstack/progress-bar'
[[module.imports]]
    path = 'github.com/hbstack/announcement-bar'
[[module.imports]]
    path = 'github.com/hbstack/blog/modules/sidebar/posts'
# mdi图标模块
[[module.imports]]
    path = 'github.com/hugomods/icons/vendors/mdi'
# 
[[module.imports]]
    path = 'github.com/hugomods/pwa'
# Twikoo评论模块
[[module.imports]]
    path = 'github.com/hbstack/blog/modules/twikoo'
# 短代码模块
[[module.imports]]
    path = 'github.com/hugomods/bootstrap'
[outputs]
  home = ['HTML', 'Offline', 'RSS', 'SearchIndex', 'WebAppManifest']
[permalinks]
  blog = '/blog/:year/:month/:title'
[taxonomies]
  authors = 'authors'
  categories = 'categories'
  series = 'series'
  tags = 'tags'
# 菜单
[params]
  [params.code_block_panel]
    max_lines = 1000
  [params.hb]
    logo = 'images/logo.png'
    [params.hb.scrollbar]
      corner_bg = '#909294'
      height = '12px'
      thumb_bg = '#909294'
      track_bg = '#f8f9fa'
      width = '12px'
    [params.hb.progress_bar]
      height = '2px'
      initial_width = 20
      interval = 50
      time = 2
    [params.hb.back_to_top]
      animation = true
      icon_height = '2em'
      icon_name = 'airplane'
      icon_width = '2em'
    # 公告栏数据
    [params.hb.announcement_bar]
      expand_stall_threshold = 1000
      interval = 5000
    [params.hb.header]
      brand = '人间只是春'
      breakpoint = 'lg'
      full_width = true
      logo_bg = 'indigo'
      menus_alignment = 'end'
      sticky = false
    # 社交链接
    [params.hb.header.socials]
        gmail = 'beilanzhisen@163.com'
    [params.hb.footer]
      site_title = '人生不过一场山川而已'
      powered_by = false
    [params.hb.blog.sidebar]
        [params.hb.blog.sidebar.profile]
          avatar = '/images/avatar.png'
          avatar_size = 100
          description = '喜马拉雅的山顶永远不会有万家灯火'
          location = 'China·HangZhou'
          title = '人间只是春'
        [params.hb.blog.sidebar.profile.socials]
             bilibili = "477276392"
             email = "beilanzhisen@163.com"
        [params.hb.blog.sidebar.taxonomies]
          count = true
          limit = 10
          separate = false
          style = 'underline'
        # 侧边栏文章
        [params.hb.blog.sidebar.posts]
          featured_count = 5
          fill = true
          list_style = 'slide'
          recent_count = 5
          style = 'underline'
    [params.hb.google_fonts]
[[params.hb.google_fonts.families]]
        name = 'Noto Sans Simplified Chinese'
[[params.hb.google_fonts.families]]
        name = 'Noto Sans Simplified Chinese'
        [params.hb.google_fonts.families.axis]
          ital = ['1']
          wght = ['600']

