main:
- name: 首页
  params:
    icon:
      name: home-edit-outline
      vendor: mdi
  url: /
  weight: 1
- name: 文章
  params:
    description: Foo description.
    icon:
      name:   post
      vendor: mdi
  url: /posts
  weight: 2
- name: 分类
  params:
    description: Foo description.
    icon:
      name:   archive
      vendor: mdi
  url: /categories
  weight: 3
- name: 标签
  params:
    description: Foo description.
    icon:
      name: tag-multiple
      vendor: mdi
  url: /tags
  weight: 4
- name: 关于
  params:
    description: Foo description.
    icon:
      name: near-me
      vendor: mdi
  url: /about
  weight: 5
- name: 友情链接
  params:
    description: Foo description.
    icon:
      name: link-edit
      vendor: mdi
  url: /friends
  weight: 6




footer:
- identifier: link1
  name: 推荐项目
- name: Kubernetes
  params:
    icon:
      color: '#03A9F4'
      name: ship-wheel
      vendor: mdi
  parent: link1
  url: "https://kubernetes.io"
- name: Apache APISIX®
  params:
    icon:
      color: '#F44336'
      name: api
      vendor: mdi
  parent: link1
  url: "https://apisix.apache.org/zh/"
- name: NGINX
  params:
    icon:
      color: '#4CAF50'
      name: alpha-n-box-outline
      vendor: mdi
  parent: link1
  url: "https://apisix.apache.org/zh/"